name: Accessibility Testing

on:
  push:
    branches:
      - main

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Lighthouse Accessibility Tests
        run: npm run accessibility-test

      - name: Save Lighthouse Reports
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-reports
          path: ./reports
